import { QueueConfig, QueueType } from './types';

export const QUEUE_CONFIGS: Record<QueueType, QueueConfig> = {
  empty: {
    id: 'empty',
    title: 'Empty Files',
    icon: '📄',
    description: 'Notes, canvas, and base files with no content',
    action: 'Add content or delete the file',
    hasBatchDelete: true,
    editAction: 'open',
  },
  missingType: {
    id: 'missingType',
    title: 'Missing Type Tag',
    icon: '🏷️',
    description: 'Notes without a type/* tag',
    action: 'Add a type/* tag to categorize this note',
    hasBatchDelete: false,
    editAction: 'open',
  },
  missingTopic: {
    id: 'missingTopic',
    title: 'Missing Topic Tag',
    icon: '📚',
    description: 'Notes without a topic/* tag',
    action: 'Add a topic/* tag or skip if not needed',
    hasBatchDelete: false,
    editAction: 'open',
  },
  untagged: {
    id: 'untagged',
    title: 'Untagged Files',
    icon: '🚫',
    description: 'Notes without any tags at all',
    action: 'Add at least a type/* tag',
    hasBatchDelete: false,
    editAction: 'open',
  },
  unfiled: {
    id: 'unfiled',
    title: 'Unfiled Files',
    icon: '📁',
    description: 'Notes in the vault root',
    action: 'Move to a folder or keep in root intentionally',
    hasBatchDelete: false,
    editAction: 'move',
  },
  misfiled: {
    id: 'misfiled',
    title: 'Misfiled Notes',
    icon: '📂',
    description: 'Notes in non-standard folders',
    action: 'Move to an allowed folder (assets, daily, templates, archived) or root',
    hasBatchDelete: false,
    editAction: 'move',
  },
  unused: {
    id: 'unused',
    title: 'Unused Assets',
    icon: '🖼️',
    description: 'Images, videos, audio, and drawings not linked anywhere',
    action: 'Link the asset in a note or delete it',
    hasBatchDelete: true,
    editAction: 'open',
  },
  orphan: {
    id: 'orphan',
    title: 'Orphan Notes',
    icon: '🔗',
    description: 'Notes with no links in or out',
    action: 'Add links to connect this note or delete if obsolete',
    hasBatchDelete: false,
    editAction: 'open',
  },
};
