import { QueueConfig, QueueType } from './types';

export const QUEUE_CONFIGS: Record<QueueType, QueueConfig> = {
  empty: {
    id: 'empty',
    title: 'Empty files',
    icon: '📄',
    description: 'Notes, canvas, and base files with no content',
    action: 'Add content or delete the file',
    editLabel: 'Edit',
    editCommand: null,
    batchAction: { label: 'Delete all', type: 'delete' },
  },
  missingType: {
    id: 'missingType',
    title: 'Missing type tag',
    icon: '🏷️',
    description: 'Notes without a type/* tag',
    action: 'Add a type/* tag to categorize this note',
    editLabel: 'Add tag',
    editCommand: 'editor:insert-tag',
    batchAction: null,
  },
  missingTopic: {
    id: 'missingTopic',
    title: 'Missing topic tag',
    icon: '📚',
    description: 'Notes without a topic/* tag',
    action: 'Add a topic/* tag or keep if not needed',
    editLabel: 'Add tag',
    editCommand: 'editor:insert-tag',
    batchAction: null,
  },
  untagged: {
    id: 'untagged',
    title: 'Untagged files',
    icon: '🚫',
    description: 'Notes without any tags at all',
    action: 'Add at least a type/* tag',
    editLabel: 'Add tag',
    editCommand: 'editor:insert-tag',
    batchAction: null,
  },
  unfiled: {
    id: 'unfiled',
    title: 'Unfiled files',
    icon: '📁',
    description: 'Notes in the vault root',
    action: 'Move to a folder or keep in root intentionally',
    editLabel: 'Move',
    editCommand: 'file-explorer:move-file',
    batchAction: null,
  },
  misfiled: {
    id: 'misfiled',
    title: 'Misfiled notes',
    icon: '📂',
    description: 'Notes in non-standard folders',
    action: 'Move to an allowed folder or root',
    editLabel: 'Move',
    editCommand: 'file-explorer:move-file',
    batchAction: { label: 'Move all to root', type: 'moveToRoot' },
  },
  unused: {
    id: 'unused',
    title: 'Unused attachments',
    icon: '🖼️',
    description: 'Images, videos, audio, and drawings not linked anywhere',
    action: 'Link the attachment in a note or delete it',
    editLabel: 'Edit',
    editCommand: null,
    batchAction: { label: 'Delete all', type: 'delete' },
  },
  orphan: {
    id: 'orphan',
    title: 'Orphan notes',
    icon: '🔗',
    description: 'Notes with no links in or out',
    action: 'Add links to connect this note or delete if obsolete',
    editLabel: 'Edit',
    editCommand: null,
    batchAction: null,
  },
  dailyTemplate: {
    id: 'dailyTemplate',
    title: 'Daily template mismatch',
    icon: '📅',
    description: 'Daily notes that don\'t match your current template structure',
    action: 'Update this note to match your daily template',
    editLabel: 'Edit',
    editCommand: null,
    batchAction: null,
  },
};
